# Generated by Django 5.0.2 on 2024-03-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0002_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vaccination_app.hospital'),
        ),
    ]
